name: Release
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js for GitHub
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com/malba231180/npm-pkg'
      - name: Set NPM Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=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" > .npmrc
          echo "@malba231180:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: list
        run: npm config ls -l
      - name: Install dependencies
        run: npm install
      - name: ci
        run: npm ci
      - name: GitHub login
        run: npm login --userconfig=.npmrc --scope=@malba231180 --registry=https://npm.pkg.github.com
      - name: GitHub Release
        run: npm publish --userconfig=/npm-pkg/.npmrc --registry=https://npm.pkg.github.com/malba231180/npm-pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js for NPM
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Release
        run: npm publish --userconfig /npm-pkg/.npmrc --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ENV_PKG_90 }}
